### ISSUE TITLE
Distribute maintainer like a binary

### ISSUE THREAD

**Issue by Dgadavin** [gaocegege/maintainer#31]
Good day. 
I want to use this tool on my Jenkins that I run in docker so I cant use docker in docker because of mount volume issue ( Also I really don't want to setup Golang and do `go get`, so my suggestion is can you distribute maintainer like a single binary, like terraform for example?[https://www.terraform.io/downloads.html](url)

Thanks a lot.

**Comment by gaocegege** [comment]
Of course, does Linux build works for you? I could build a binary in Linux for you and push it to GitHub.

**Comment by Dgadavin** [comment]
Yes. Sounds good. What deps should I install?

**Comment by gaocegege** [comment]
Yeah, I think it is enough. If you have go installed, you could run `go get github.com/gaocegege/maintainer` to install the binary to $GOPATH/bin/ :0 Or you could download the binary from <TODO>

**Comment by gaocegege** [comment]
Does it works for you?

:smiley:

**Comment by Dgadavin** [comment]
Yes. Thanks a lot. It's work for me.
