### ISSUE TITLE
Improve AUTHORS layout

### ISSUE THREAD

**Issue by myii** [gaocegege/maintainer#37]
@gaocegege Thanks for this application, finding it very useful.  We've forked the repository to make use of more of the available data.  You can see how it looks here:

* https://github.com/saltstack-formulas/template-formula/blob/master/AUTHORS.md

Shall I prepare a PR for you here?

**Comment by gaocegege** [comment]
@myii Your fork is really awesome! Welcome PR!

**Comment by myii** [comment]
@gaocegege Really sorry, I've been very busy.  I'll try to do this during this week sometime.

**Comment by gaocegege** [comment]
@myii No worry, Feel free to contribute.

**Comment by myii** [comment]
@gaocegege It took me more than a week!  Actually, the recent updates forced me to rebase my fork, so it became an opportunity to prepare PR #38.  I hope you like it!

**Comment by gaocegege** [comment]
Thanks for the PR! I like it! :tada:
