### ISSUE TITLE
CONTRIBUTION.md can't display the format of commit message normally

### ISSUE THREAD

**Issue by Faldict** [gaocegege/maintainer#4]
I think the tabs between \<code\> and \</code\> have been transferred. So may be you should add `\`.

**Comment by gaocegege** [comment]
Yeah, It is a bug.

Actually I tried to use ``` but it seems that golang misunderstands it with raw strings.

Thanks, I'll fix it.

**Comment by Faldict** [comment]
高策哥哥怎么有这么多时间开新坑 @gaocegege

**Comment by gaocegege** [comment]
@Faldict Actually, this repo costs me only 5 hours.

鲁迅说过，时间就像XX，挤一下就有了

**Comment by gaocegege** [comment]
而且还有一点，很多坑都不维护了，所以时间就多了。。

**Comment by gaocegege** [comment]
Partially done, if you are not satisfied, feel free to reopen the issue.
